name: 'Execução Manual'

on:
  workflow_dispatch:

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Configurando Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Instalando dependências
        run: npm ci

      - name: Executando testes
        run: npx mocha tests/trabalho-final.js